# Generated by Django 4.2.9 on 2024-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
