# Generated by Django 4.2.9 on 2024-01-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_variacao_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
